version: 2
updates:
  - package-ecosystem: pip
    directories:
      - "/"
      - "/api"
      - "/document_processor"
      - "/embedder_service"
      - "/reranker_service"
    schedule:
      interval: monthly
      timezone: Europe/Moscow
    groups:
      python-dependencies:
        patterns:
          - "*"

  - package-ecosystem: docker
    directories:
      - "/api"
      - "/document_processor"
      - "/embedder_service"
      - "/reranker_service"
      - "/web"
    schedule:
      interval: monthly
      timezone: Europe/Moscow
    groups:
      docker-images:
        patterns:
          - "*"

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: monthly
      timezone: Europe/Moscow
    groups:
      github-actions:
        patterns:
          - "*"
